---
sidebar: sidebar 
permalink: cs_restrict_user_access.html 
keywords: alert, snapshot,  attack 
summary: Cloud Secure를 사용하면 사보타업 혐의가 있는 경우 사용자 액세스를 제한할 수 있습니다 
---
= 사용자 액세스를 제한합니다


[role="lead"]
공격이 감지되면 Cloud Secure는 파일 시스템에 대한 사용자 액세스를 제한하여 공격을 차단할 수 있습니다. 자동 응답 정책을 사용하거나 알림 또는 사용자 세부 정보 페이지에서 수동으로 액세스를 제한할 수 있습니다.

사용자 액세스를 제한할 때는 액세스 제한 유형(블록 또는 읽기 전용) 및 기간을 정의해야 합니다. 선택한 기간이 끝나면 사용자 액세스가 자동으로 복원됩니다.

액세스 제한은 SMB 및 NFS 프로토콜 모두에 대해 지원됩니다.

호스트 시스템의 IP 주소를 통해 제한되며, 이는 사용자가 스토리지에 액세스한 컴퓨터를 의미합니다. 이러한 머신 IP 주소는 Cloud Secure에서 모니터링하는 SVM(스토리지 가상 머신)에 액세스하지 못하도록 차단됩니다.

예를 들어, Cloud Secure이 10개의 SVM을 관리하고 4개의 SVM에 대해 자동 응답 정책을 구성한다고 가정해 보겠습니다. 4개의 SVM 중 하나에서 공격이 발생한 경우 10개의 SVM 모두에서 사용자의 액세스가 제한됩니다. 원래 SVM에 대해 스냅샷이 여전히 촬영됩니다.

CIFS에 대해 SVM이 4개, NFS용으로 구성된 SVM이 1개 있고, 나머지 2개는 NFS와 CIFS 모두에 대해 구성된 경우 4개의 SVM 중 하나에서 공격이 발생하면 모든 SVM이 차단됩니다.



=== 사용자 액세스 제한을 위한 필수 구성 요소

이 기능을 사용하려면 고객은 SMB 및 NFS에 대한 엑스포트 정책을 구성해야 합니다. Data Source Collector에서 NFS 및 SMB가 구성된 경우 아래 단계를 따르십시오.

NFS의 경우 내보내기 정책이 기본적으로 구성됩니다. 기본적으로, SVM에서 NFS 서비스를 생성할 때 엑스포트 정책이 생성됩니다. SMB의 경우 내보내기 정책을 구성해야 합니다.

NFS와 SMB 모두에 대해 _csroles_를 올바르게 구성해야 합니다. 고객은 에 설명된 대로 ONTAP SVM 데이터 소스 수집기를 설정할 때 _csrole_(아직 구성하지 않은 경우)을 구성해야 합니다 link:task_add_collector_svm.html#a-note-about-permissions["데이터 수집기 권한"] 문서화:

클러스터 IP를 사용하여 데이터 수집기를 구성하는 경우 ONTAP 명령줄에서 다음을 수행합니다.

 security login role create -role csrole -cmddirname "vserver export-policy rule" -access all
서버 IP를 사용하여 데이터 수집기를 구성하는 경우 ONTAP 명령줄에서 다음을 수행하여 올바른 _<vservername>_을(를) 삽입합니다.

 security login role create -vserver <vservername> -role csrole -cmddirname "vserver export-policy rule" -access all
기본적으로 SVM에서 NFS 서비스를 생성할 때 엑스포트 정책이 생성됩니다.

다음은 내보내기 정책을 구성하는 명령입니다. 아래 명령을 텍스트 편집기에 복사하고 <vserver> 이름을 가상 서버의 이름으로 바꾸십시오. 그런 다음 각 라인을 한 번에 하나씩 복사하고 ONTAP 콘솔에서 실행합니다. 참고: 명령을 실행하기 전에 먼저 고급 모드로 전환해야 합니다.


TIP: 이 기능은 PoC를 실행하는 데 특히 유용합니다. 테스트할 시스템에서 SMB는 아래와 같이 구성할 수 있습니다. PoC 중에 Data Source Collector에서 SMB/CIFS 프로토콜만 사용하도록 설정하고 NFS 프로토콜을 해제합니다.

클러스터 모드를 사용하는 경우:

 security login role create -role csrole -cmddirname "vserver export-policy rule" -access all -query "-policyname cloudsecure_*"
SVM 모드를 사용하는 경우:

보안 로그인 역할 create -vserver <vservername> -role csrole -cmddirname "vserver export -policy rule" -access all-query" -policyname cloudsecure_ *"

두 모드 모두에서 다음 명령을 실행합니다.

....
set -privilege advanced
cifs options modify -is-exportpolicy-enabled true -vserver <vserver>
export-policy rule create -vserver <vserver> -policyname default -protocol cifs -clientmatch 0.0.0.0/0 -rorule any -rwrule any
....
exportpolicy_and_exportpolicy rule_이(가) 올바르게 구성되었는지 확인하려면 위의 명령을 실행한 후 다음 명령을 실행합니다.

....
cifs options show  -fields is-exportpolicy-enabled -vserver <vserver>
export-policy show -vserver <vserver>
export-policy rule show -policyname default -vserver <vserver>
....


=== 이 기능을 활성화하는 방법은 무엇입니까?

* Cloud Secure에서 * 관리자 > 자동 응답 정책 > 응답 정책 설정 > 액세스 제한 * 으로 이동합니다.
* "사용자 액세스 제한 활성화"를 _ENABLED_로 설정합니다.




=== 자동 사용자 액세스 제한을 설정하는 방법은 무엇입니까?

* 새 공격 정책을 만들거나 기존 공격 정책을 편집합니다.
* 공격 정책을 모니터링해야 하는 SVM을 선택합니다.
* "사용자 IP 파일 액세스 제한" 확인란을 클릭합니다. 이 옵션을 선택하면 기능이 활성화됩니다.
* “Limit User Access(사용자 액세스 제한)”에서 적용할 제한 모드를 선택합니다.
* “Time Period(기간)”에서 제한을 적용할 시간을 선택합니다.
* 자동 제한을 테스트하려면 을 통해 공격을 시뮬레이션할 수 있습니다 link:concept_cs_attack_simulator.html["시뮬레이션된 스크립트"].




=== 시스템에 제한된 사용자가 있는지 어떻게 알 수 있습니까?

* 경고 목록 페이지에서 사용자가 제한되는 경우 화면 상단에 배너가 표시됩니다.
* 배너를 클릭하면 "사용자" 페이지로 이동합니다. 에서 제한된 사용자 목록을 볼 수 있습니다.
* “Users(사용자)” 페이지에는 “IP Access(IP 액세스)”라는 열이 있습니다. 이 열에서 현재 사용자 제한 상태가 표시됩니다.




=== 사용자 액세스를 수동으로 제한 및 관리합니다

* 경고 세부 정보 또는 사용자 세부 정보 화면으로 이동한 다음 해당 화면에서 사용자를 수동으로 제한하거나 제한하지 않도록 설정할 수 있습니다.




=== 사용자가 액세스 기록을 제한합니다

경고 세부 정보 및 사용자 세부 정보 페이지의 사용자 패널에서 사용자의 액세스 제한 기록(시간, 작업(블록, 읽기 전용, 복원), 기간, 수동/자동 및 영향을 받는 IP에 의해 수행되는 작업입니다.



=== 이 기능을 비활성화하는 방법은 무엇입니까?

언제든지 이 기능을 비활성화할 수 있습니다. 시스템에 제한된 사용자가 있는 경우 먼저 액세스 권한을 복원해야 합니다.

* Cloud Secure에서 * 관리자 > 자동 응답 정책 > 응답 정책 설정 > 액세스 제한 * 으로 이동합니다
* "사용자 액세스 제한 활성화"를 선택 해제하여 비활성화합니다.


이 기능은 모든 페이지에서 숨겨집니다.



== 문제 해결

|===
| 문제 | 시도해 보십시오 


| 일부 사용자는 공격이 있어도 제한을 받지 않습니다. | SVM용 Data Collector 및 Agent가 _Running_상태인지 확인합니다. 데이터 수집기 및 에이전트가 중지된 경우 Cloud Secure에서 명령을 전송할 수 없습니다. 이는 사용자가 이전에 사용되지 않은 새 IP가 있는 시스템에서 스토리지에 액세스했을 수 있기 때문입니다. 제한은 사용자가 스토리지에 액세스하는 데 사용하는 호스트의 IP 주소를 통해 수행됩니다. 제한된 IP 주소 목록을 보려면 UI(알림 세부 정보 > 이 사용자의 액세스 제한 기록 > 영향을 받는 IP)를 확인하십시오. 사용자가 제한된 IP와 다른 IP를 가진 호스트에서 스토리지에 액세스하는 경우 사용자는 여전히 제한되지 않은 IP를 통해 스토리지를 액세스할 수 있습니다. 사용자가 IP가 제한된 호스트에서 액세스를 시도하는 경우 스토리지를 액세스할 수 없습니다. 


| 액세스 제한을 수동으로 클릭하면 “작업에 대한 사용자 IP가 없습니다.”가 나타납니다. | 제한할 IP가 이미 다른 사용자로부터 제한되어 있습니다. 


| "SMB 프로토콜의 내보내기 정책 사용이 SVM에 대해 비활성화되었습니다."라는 경고와 함께 액세스 제한 이 실패합니다. 사용자 액세스 제한 기능을 사용하도록 엑스포트 정책 사용 허용" | 필수 구성 요소에 설명된 대로 가상 서버에 대해 -is-exportpolicy-enabled 옵션이 true 인지 확인합니다. 
|===