---
sidebar: sidebar 
permalink: pre-requisites_for_k8s_operator.html 
keywords: telegraf, installation, install, agent, telegraf agent, kubernetes, eks, operator, k8s 
summary: Cloud Insights는 Kubernetes에서 통합 데이터를 수집하는 에이전트로 Teleraf를 지원합니다. 
---
= NetApp Kubernetes 모니터링 운영자를 설치 또는 업그레이드하기 전에
:toc: macro
:hardbreaks:
:toclevels: 2
:allow-uri-read: 
:toc: 
:nofooter: 
:toclevels: 2
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
를 설치 또는 업그레이드하기 전에 이 정보를 읽으십시오 link:task_config_telegraf_agent_k8s.html["Kubernetes 모니터링 운영자"].



=== 전제 조건:

|===
| 구성 요소 | 요구 사항 


| Kubernetes 버전 | Kubernetes v1.20 이상 


| Kubernetes 배포 | AWS EKS(Elastic Kubernetes Service)
Azure Kubernetes 서비스(AKS)
Google Kubernetes Engine(GKE)
Red Hat OpenShift
RKE(Rancher Kubernetes Engine)
VMware Tanzu입니다 


| 리눅스 OS | Cloud Insights은 Arm64 아키텍처에서 실행되는 노드를 지원하지 않습니다.

네트워크 모니터링: Linux 커널 버전 4.18.0 이상을 실행해야 합니다. Photon OS는 지원되지 않습니다. 


| 라벨 | Cloud Insights는 Linux를 실행하는 Kubernetes 노드 모니터링을 지원하며, 이들 플랫폼에서 다음 Kubernetes 레이블을 찾는 Kubernetes 노드 선택기를 지정합니다.

Kubernetes v1.20 이상: Kubernetes.IO/OS = Linux
Rancher + Cates.io 오케스트레이션/Kubernetes 플랫폼: cool.io/OS = Linux 


| 명령 | curl 및 kubectl 명령을 사용할 수 있어야 합니다. 최상의 결과를 얻으려면 이러한 명령을 경로에 추가하십시오. 


| 연결성 | kubectl CLI는 대상 K8s 클러스터와 통신하도록 구성되고 Cloud Insights 환경에 인터넷이 연결됩니다.

설치하는 동안 프록시 뒤에 있는 경우 의 지침을 따릅니다 link:/task_config_telegraf_agent_k8s.html#configuring-proxy-support["프록시 지원을 구성하는 중입니다"] 작업자 설치의 섹션.

정확한 감사 및 데이터 보고를 위해 NTP(Network Time Protocol) 또는 SNTP(Simple Network Time Protocol)를 사용하여 Agent 시스템의 시간을 동기화합니다. 


| 기타 | OpenShift 4.6 이상에서 실행 중인 경우 다음 링크를 따라야 합니다. task_config_telegraf_agent_k8s.html#openshift-instructions [OpenShift Instructions] 


| API 토큰 | Operator를 다시 배포하는 경우(예: 업데이트 또는 교체) 새 API 토큰을 생성할 필요가 없습니다. 이전 토큰을 다시 사용할 수 있습니다. 
|===


=== 오퍼레이터 구성

새로운 버전의 연산자에서는 가장 일반적으로 수정된 설정을 _AgentConfiguration_custom 리소스에서 구성할 수 있습니다. 운용자를 배포하기 전에 _operator-config.YAML_file을 편집하여 이 리소스를 편집할 수 있습니다. 이 파일에는 일부 설정의 주석 처리된 예제가 포함되어 있습니다. 의 목록을 참조하십시오 link:telegraf_agent_k8s_config_options.html["사용 가능한 설정"] 를 참조하십시오.

다음 명령을 사용하여 연산자를 배포한 후에도 이 리소스를 편집할 수 있습니다.

 kubectl -n netapp-monitoring edit AgentConfiguration
배포된 버전의 운영자가 AgentConfiguration을 지원하는지 확인하려면 다음 명령을 실행합니다.

 kubectl get crd agentconfigurations.monitoring.netapp.com
"서버에서 오류 발생(NotFound)" 메시지가 표시되는 경우 AgentConfiguration을 사용하려면 먼저 연산자를 업그레이드해야 합니다.



=== 톨레러스와 얼룩을 볼 수 있습니다

NetApp-CI-Telegraf-DS_,_netapp-ci-fluent-bit-DS_ 및_netapp-ci-net-observer-L4-DS_Demets는 모든 노드에서 데이터를 올바르게 수집하기 위해 클러스터의 모든 노드에 Pod를 예약해야 합니다. 운용자는 잘 알려진 일부 * 얼룩을 견딜 수 있도록 구성되었습니다. 노드에서 사용자 지정 얼룩을 구성하여 모든 노드에서 Pod가 실행되지 않도록 하는 경우 이러한 얼룩에 대해 * 공차 * 를 생성할 수 있습니다 link:telegraf_agent_k8s_config_options.html["상담원 구성 _ 에서"]. 클러스터의 모든 노드에 사용자 지정 얼룩을 적용한 경우 운영자 포드를 예약 및 실행할 수 있도록 운영자 구축에 필요한 허용 오차도 추가해야 합니다.

Kubernetes에 대해 자세히 알아보십시오 link:https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/["오염과 내약입니다"].

로 돌아갑니다 link:task_config_telegraf_agent_k8s.html["* NetApp Kubernetes 모니터링 오퍼레이터 설치 * 페이지"]
