---
sidebar: sidebar 
permalink: security_admin_tool.html 
summary: Cloud Insights는 릴리즈 라이프사이클 전반에서 보안 모범 사례를 준수합니다. 
keywords: security, risk, protection 
---
= SecurityAdmin 도구
:allow-uri-read: 


[role="lead"]
CI에는 Insight 환경을 강화된 보안으로 운영할 수 있는 보안 기능이 포함되어 있습니다. 암호화, 암호 해싱의 개선, 암호를 암호화하고 해독하는 내부 사용자 암호 및 키 쌍 변경 기능이 포함되어 있습니다.

중요 데이터를 보호하려면 설치 또는 업그레이드 후에 기본 키와 취득 사용자 암호를 변경하는 것이 좋습니다.

데이터 소스 암호화된 암호는 Cloud Insights에 저장되며, 사용자가 데이터 수집기 구성 페이지에 암호를 입력할 때 공개 키를 사용하여 암호를 암호화합니다. Cloud Insights에는 데이터 수집기 암호를 해독하는 데 필요한 개인 키가 없습니다. 획득 유닛에만 데이터 수집기 암호를 해독하는 데 필요한 데이터 수집기 개인 키가 있습니다.



== 업그레이드 및 설치 고려 사항

Insight 시스템에 기본이 아닌 보안 구성(예: 암호 키 다시 입력)이 포함된 경우 보안 구성을 백업해야 합니다. 새 소프트웨어를 설치하거나 소프트웨어를 업그레이드하는 경우 시스템을 기본 보안 구성으로 되돌립니다. 시스템이 기본 구성으로 복원되면 시스템이 올바르게 작동하려면 기본이 아닌 구성을 복원해야 합니다.



== 획득 장치의 보안 관리

SecurityAdmin 도구를 사용하면 Cloud Insights에 대한 보안 옵션을 관리할 수 있으며 획득 장치 시스템에서 실행됩니다. 보안 관리에는 키 및 암호 관리, 사용자가 만들고 복원한 보안 구성을 기본 설정으로 저장 및 복원하는 작업이 포함됩니다.



== 시작하기 전에

보안 구성 작업을 수행하려면 AU 시스템에 대한 관리자 권한이 있어야 합니다.

이 작업 정보 SecurityAdmin 도구는 다음 위치 중 하나에 있는 획득 장치 시스템에서 찾을 수 있습니다.

* * Windows-C:\Program Files\SANscreen\SecurityAdmin\bin\securityadmin.bat
* Linux -/bin/oci-securityadmin.sh


.단계
* * 대화형 모드(-I)에서 SecurityAdmin 도구를 시작합니다.
+
다음 옵션이 표시됩니다.

* 백업
+
모든 암호 및 키가 포함된 볼트의 백업 zip 파일을 작성하고 사용자가 지정한 위치 또는 다음 기본 위치에 파일을 배치합니다.

+
....
Windows - C:\Program Files\SANscreen\backup\vault
Linux - /var/log/netapp/oci/backup/vault
....
* 복원
+
작성된 볼트의 zip 백업을 복원합니다. 복원되면 모든 암호와 키는 백업 생성 시 기존 값으로 되돌려집니다.

+
복원을 사용하여 여러 서버의 암호와 키를 동기화할 수 있습니다. 예를 들어: - AU에서 암호화 키 변경 - 볼트 백업 작성 - AUS 각각에 볼트 백업을 복원합니다

* 암호화 키를 변경합니다
+
장치 암호를 암호화 또는 해독하는 데 사용되는 AU 암호화 키를 변경합니다.

+
암호화 키를 변경할 때는 업그레이드 또는 설치 후 복원할 수 있도록 새 보안 구성을 백업해야 합니다.

* 암호 업데이트
+
'촬영' 사용자 계정의 암호를 변경합니다.

+
암호를 변경할 때 필요한 경우 복원할 수 있도록 새 보안 구성을 백업해야 합니다.

* 기본값으로 재설정합니다
+
획득 사용자 암호 및 획득 사용자 암호화 키를 기본값으로 재설정합니다. 기본값은 설치 중에 제공되는 값입니다.

* Exit(종료)
+
SecurityAdmin 도구를 종료합니다.



구성할 옵션을 선택하고 화면의 지시를 따릅니다.
