---
sidebar: sidebar 
permalink: task_troubleshooting_general_problems.html 
summary: 일반 Cloud Insights 문제 해결 팁 
keywords: troubleshooting, problems, browser, login, log in, accessing, access to, Trident, qtree, quota 
---
= 일반적인 Cloud Insights 문제 해결
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
여기에서 Cloud Insights 문제 해결을 위한 제안 사항을 찾을 수 있습니다.

도 참조하십시오 link:task_troubleshooting_linux_acquisition_unit_problems.html["Linux 획득 장치 문제 해결"] 및 link:task_troubleshooting_windows_acquisition_unit_problems.html["Windows 획득 장치 문제 해결"].



== 로그인 문제

|===
| * 문제: * | * 사용해 보세요. * 


| Cloud Insights는 5분마다 로그아웃합니다 | 396149d67edd166e53b49c38f4b707ba 


| e4ff2e59dd571d2bbd5a906b6fad2546 | a9a216fbb1fb9d774e7cedfcf74c00cf 


| Cloud Insights에 초대를 받았는데 "승인되지 않음" 메시지가 나타납니다. | 199017f1d912993f091b6b969d3442ad 


| 176f8c6fa466059df49f2717c021d306 | 7a8624fb56224e907698f45ef2e4cc47 


| 며칠 후에 자동으로 로그아웃되었습니다. | ed6e79e2f9b9c201ed834c6efeb7f356 


| "더 이상 로그인할 수 없습니다"라는 오류 메시지가 나타납니다. | acf29dcaa06698c29122cba5402e3145 


| 기타 로그인 오류 | Chrome에서 시크릿 모드를 시도하거나 브라우저 기록, 쿠키 및 캐시를 지웁니다. 다른 브라우저 프로필(예 Chrome - 사람 추가). 
|===


== 기타 문제

|===


| * 질문: * | * 답변: * 


| Qtree 하드 할당량이 쿼리에 올바르게 표시되지만 소프트 할당량이 볼륨의 총 용량으로 표시됩니다. 맞습니까? | 수동으로 설정하거나 Trident를 통해 설정하는 하드 할당량만 설정된 할당량으로 표시됩니다. 하드 할당량을 지정하지 않으면 Qtree 용량이 내부 볼륨 용량이 됩니다. 


| 동일한 Qtree에 수동으로 소프트 할당량과 하드 할당량이 모두 설정되어 있지만 표시되는 총 용량은 하드 할당량입니다. 맞습니까? | 예. 하드 할당량이 지정된 경우 총 용량으로 표시됩니다. 


| Cognos 보고서 일정 시간을 입력할 때 일정 시간에 "m"이 추가로 나타나는 경우가 있습니다. 예를 들어 시간을 "02:15 PM"으로 입력하면 "02:15 PMM"(또는 PMM)이라는 추가 문자를 추가할 수 있습니다. 바깥쪽을 클릭하면 "오전 2:15"로 변경됩니다.

보고서를 저장할 수 있지만 저장된 보고서를 다시 열면 일정 시간에 AM 또는 PM을 입력했는지 여부에 관계없이 예약 시간이 오전(예: 오전)으로 표시됩니다. | 예약 시간을 다시 입력하십시오. 전체 "AM" 또는 "PM" 문자를 입력하지 않도록 주의하십시오. "AM"에는 "A"를, "PM"에는 "P"를 입력하면 됩니다. 추가 문자가 표시되지 않으면 예약 시간이 올바르게 설정됩니다. 
|===


== 리소스

추가 문제 해결 팁은 에서 찾을 수 있습니다 link:https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Cloud_Insights["NetApp 기술 자료"] (지원 로그인 필요)

추가 지원 정보는 Cloud Insights에서 확인할 수 있습니다 link:concept_requesting_support.html["지원"] 페이지.

활성 Cloud Insights 구독이 있는 경우 다음 지원 옵션을 사용할 수 있습니다.

link:https://www.netapp.com/us/contact-us/support.aspx["전화"]
link:https://mysupport.netapp.com/site/cases/mine/create?serialNumber=95001014387268156333["지원 티켓"]

자세한 내용은 를 참조하십시오 https://docs.netapp.com/us-en/cloudinsights/concept_requesting_support.html["Cloud Insights 지원 문서"].
