---
sidebar: sidebar 
permalink: task_dc_na_ontap_rest.html 
keywords: data collector, ontap, ontap, CDOT, REST 
summary: ONTAP REST 데이터 수집기 
---
= NetApp ONTAP REST 데이터 수집기
:hardbreaks:
:toclevels: 2
:allow-uri-read: 
:toclevels: 2
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
이 데이터 수집기는 ONTAP 계정의 읽기 전용 REST API 호출을 사용하여 ONTAP를 실행하는 스토리지 시스템에서 인벤토리 및 성능 데이터를 수집합니다. 또한 이 데이터 수집기는 지원을 가속화하기 위해 클러스터 응용 프로그램 레지스트리에 레코드를 만듭니다.



== 용어

Cloud Insights는 ONTAP 데이터 수집기에서 인벤토리 및 성능 데이터를 가져옵니다. 획득한 각 자산 유형에 대해 자산에 가장 일반적으로 사용되는 용어가 표시됩니다. 이 데이터 수집기를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

[cols="2*"]
|===
| 공급업체/모델 기간 | Cloud Insights 용어입니다 


| 디스크 | 디스크 


| RAID 그룹 | 디스크 그룹 


| 클러스터 | 스토리지 


| 노드 | 스토리지 노드 


| 집계 | 스토리지 풀 


| LUN을 클릭합니다 | 볼륨 


| 볼륨 | 내부 볼륨 
|===


== ONTAP 데이터 관리 용어

다음 용어는 ONTAP 데이터 관리 스토리지 자산 랜딩 페이지에서 찾을 수 있는 오브젝트 또는 참조에 적용됩니다. 이러한 용어 중 다수는 다른 데이터 수집기에도 적용됩니다.



=== 스토리지

* 모델 – 이 클러스터 내에서 쉼표로 구분된 고유한 개별 노드 모델 이름의 목록입니다. 클러스터의 모든 노드가 동일한 모델 유형인 경우 하나의 모델 이름만 표시됩니다.
* 공급업체 - 동일한 공급업체 이름 새 데이터 소스를 구성하는 경우 표시됩니다.
* 일련 번호 – 스토리지 일련 번호입니다. ONTAP 데이터 관리와 같은 클러스터 아키텍처 스토리지 시스템에서 이 일련 번호는 개별 "스토리지 노드" 일련 번호보다 덜 유용할 수 있습니다.
* IP – 일반적으로 데이터 소스에 구성된 IP 또는 호스트 이름이 됩니다.
* 마이크로코드 버전 – 펌웨어.
* 물리적 용량 – 역할에 관계없이 시스템의 모든 물리적 디스크에 대한 기본 2의 합계.
* 지연 시간 – 읽기 및 쓰기 모두에서 호스트에서 발생하는 워크로드를 나타냅니다. Cloud Insights는 이러한 가치를 직접 소싱하는 것이 가장 바람직하지만, 이는 종종 그렇지 않습니다. 이러한 기능을 제공하는 스토리지 대신 Cloud Insights는 일반적으로 개별 내부 볼륨의 통계에서 파생된 IOP 가중 계산을 수행합니다.
* 처리량 – 내부 볼륨에서 집계됩니다. 관리 - 장치의 관리 인터페이스에 대한 하이퍼링크가 포함될 수 있습니다. 인벤토리 보고의 일부로 Cloud Insights 데이터 소스에서 프로그래밍 방식으로 만듭니다.




=== 스토리지 풀

* 스토리지 – 이 풀이 상주하는 스토리지 시스템입니다. 필수입니다.
* 형식 - 가능성 목록 목록의 설명 값입니다. 일반적으로 "집계" 또는 "RAID 그룹"이 됩니다.
* 노드 – 이 스토리지 배열의 아키텍처가 특정 스토리지 노드에 속해 있는 경우, 이 스토리지 배열의 이름은 해당 랜딩 페이지의 하이퍼링크로 표시됩니다.
* Flash Pool 사용 – 예/아니요 가치 – 이 SATA/SAS 기반 풀에 캐싱 가속화에 SSD가 사용됩니까?
* 중복 – RAID 레벨 또는 보호 체계. RAID_DP는 이중 패리티이고, RAID_TP는 삼중 패리티입니다.
* 용량 – 이 값은 논리적 사용 용량, 가용 용량 및 총 논리적 용량, 그리고 이 용량 전체에서 사용된 비율입니다.
* 과도하게 커밋된 용량 – 효율성 기술을 사용하여 스토리지 풀의 논리적 용량보다 큰 볼륨 또는 내부 볼륨 용량의 합계를 할당한 경우 여기에 있는 백분율 값은 0%보다 큽니다.
* 스냅샷 – 스토리지 풀 아키텍처가 스냅샷 전용 영역에 해당 용량의 일부를 할당하는 경우 사용된 스냅샷 용량 및 총 용량입니다. MetroCluster 구성의 ONTAP는 이 문제를 나타낼 가능성이 높지만, 다른 ONTAP 구성은 더 적습니다.
* 사용률 – 이 스토리지 풀에 용량을 제공하는 모든 디스크의 사용 중 가장 높은 비율을 나타내는 백분율 값입니다. 디스크 사용률이 반드시 스토리지 성능과 강력한 상관 관계가 있는 것은 아닙니다. 호스트 기반 워크로드가 없을 경우 디스크 재구축, 중복 제거 작업 등으로 인해 사용률이 높을 수 있습니다. 또한 많은 스토리지의 복제 구현으로 인해 디스크 사용률이 높아지고 내부 볼륨 또는 볼륨 작업 부하로 표시되지 않을 수 있습니다.
* IOPS – 이 스토리지 풀에 용량을 제공하는 모든 디스크의 IOPS 합계입니다. 처리량 – 이 스토리지 풀에 용량을 제공하는 모든 디스크의 총 처리량입니다.




=== 스토리지 노드

* 스토리지 – 이 노드가 속한 스토리지 시스템입니다. 필수입니다.
* HA 파트너 – 노드가 1개 노드로 페일오버되고 다른 1개 노드만 페일오버되는 플랫폼에서는 일반적으로 이 노드에 표시됩니다.
* 상태 - 노드의 상태입니다. 배열이 데이터 소스에 의해 인벤토리를 작성할 수 있을 만큼 양호한 경우에만 사용할 수 있습니다.
* 모델 - 노드의 모델 이름입니다.
* 버전 - 디바이스의 버전 이름입니다.
* 일련 번호 - 노드 일련 번호입니다.
* 메모리 – 사용 가능한 경우 베이스 2 메모리.
* 사용률 – ONTAP에서는 독점 알고리즘의 컨트롤러 스트레스 인덱스입니다. 성능 폴링이 발생할 때마다 WAFL 디스크 경합 또는 평균 CPU 사용률의 증가인 0에서 100% 사이의 숫자가 보고됩니다. 값이 50%를 넘는 지속적인 값이 관찰될 경우, 이는 낮은 크기 조정을 나타내는 것입니다. 컨트롤러/노드가 충분히 크지 않거나 회전 디스크가 부족하여 쓰기 워크로드를 흡수할 수 없습니다.
* IOPS – 노드 개체의 ONTAP REST 호출에서 직접 파생됩니다.
* 지연 시간 – 노드 개체의 ONTAP REST 호출에서 직접 파생됩니다.
* 처리량 – 노드 개체의 ONTAP REST 호출에서 직접 파생됩니다.
* 프로세서 - CPU 수입니다.




== 요구 사항

다음은 이 데이터 수집기를 구성하고 사용하기 위한 요구 사항입니다.

* 읽기 전용 REST API 호출용으로 구성된 Administrator 계정에 대한 액세스 권한이 있어야 합니다.
* 계정 세부 정보에는 사용자 이름 및 암호가 포함됩니다.
* 포트 요구 사항: 80 또는 443
* 계정 권한:
+
** 기본 SVM에 대해 ontapi 애플리케이션에 대한 읽기 전용 역할 이름
** 추가적인 선택적 쓰기 권한이 필요할 수 있습니다. 아래의 사용 권한에 대한 참고 사항을 참조하십시오.


* ONTAP 라이센스 요구 사항:
+
** 파이버 채널 검색에 필요한 FCP 라이센스 및 매핑/마스킹된 볼륨






== 구성

[cols="2*"]
|===
| 필드에 입력합니다 | 설명 


| ONTAP 관리 IP 주소입니다 | NetApp 클러스터의 IP 주소 또는 정규화된 도메인 이름입니다 


| ONTAP REST 사용자 이름입니다 | NetApp 클러스터의 사용자 이름입니다 


| ONTAP REST 암호입니다 | NetApp 클러스터의 암호입니다 
|===


== 고급 구성

[cols="2*"]
|===
| 필드에 입력합니다 | 설명 


| 재고 폴링 간격(분) | 기본값은 60분입니다. 


| 성능 폴링 간격(초) | 기본값은 60초입니다. 


| 고급 카운터 데이터 수집 | ONTAP 고급 카운터 데이터를 폴에 포함하려면 이 옵션을 선택합니다. 


| EMS 이벤트 수집을 활성화합니다 | ONTAP EMS 로그 이벤트 데이터를 포함하려면 선택합니다. 


| EMS 폴링 간격(초) | 기본값은 60초입니다. 
|===


== ONTAP 전력 측정 기준

여러 ONTAP 모델은 Cloud Insights에 대한 전력 메트릭을 제공하므로 모니터링 또는 알림에 사용할 수 있습니다. 아래의 지원 모델과 지원되지 않는 모델 목록은 포괄하지는 않지만 몇 가지 지침을 제공해야 합니다. 일반적으로 모델이 목록에 있는 모델과 동일한 제품군에 속하는 경우 지원은 동일해야 합니다.

지원되는 모델:

A200
A220
A250
A300
A320
A400
A700
A700s를 참조하십시오
A800
A900
C190
FAS2240-4
FAS2552
FAS2650
FAS2720
FAS2750
FAS8200
FAS8300
FAS8700
FAS9000

지원되지 않는 모델:

FAS2620
FAS3250
FAS3270
500f로 설정합니다
FAS6280
FAS/AFF 8020
FAS/AFF 8040
FAS/AFF 8060
FAS/AFF 8080



== 사용 권한에 대한 참고 사항

많은 Cloud Insights의 ONTAP 대시보드는 고급 ONTAP 카운터를 사용하기 때문에 데이터 수집기 고급 구성 섹션에서 * 고급 카운터 데이터 수집 * 을 활성화해야 합니다.

또한 ONTAP REST API에 대한 쓰기 권한이 활성화되어 있는지 확인해야 합니다. 이 경우 일반적으로 필요한 권한이 있는 클러스터 수준의 계정이 필요합니다.

클러스터 수준에서 Cloud Insights에 대한 로컬 계정을 생성하려면 클러스터 관리 관리자 사용자 이름/암호를 사용하여 ONTAP에 로그인하고 ONTAP 서버에서 다음 명령을 실행합니다.

. 시작하기 전에 _관리자_계정으로 ONTAP에 로그인해야 하며 _DIAGNOSTIC-LEVEL 명령_ 을 활성화해야 합니다.
. 다음 명령을 사용하여 역할을 생성합니다.


보안 로그인 REST-ROLE CREATE-ROLE {ROLE NAME} - api/api-access readonly
보안 로그인 REST-ROLE CREATE-ROLE {ROLE NAME} - api/api/cluster/agent - 모두 액세스

SVM 서비스 웹 액세스 create-name spi-role {role name}-vserver{name from above command}
security login create -user-or -group-name {username} -application http-authentication -method password -role {role name}

....
 ////
security login role create -role ci_readonly -cmddirname DEFAULT -access readonly
 security login role create -role ci_readonly -cmddirname security -access readonly
 security login role create -role ci_readonly -access all -cmddirname {cluster application-record create}
 ////
....
. 다음 명령을 사용하여 읽기 전용 사용자를 생성합니다. create 명령을 실행하면 이 사용자의 암호를 입력하라는 메시지가 표시됩니다.
+
 security login create -username ci_user -application ontapi -authentication-method password -role ci_readonly


AD/LDAP 계정을 사용하는 경우 명령은 여야 합니다

 security login create -user-or-group-name DOMAIN\aduser/adgroup -application ontapi -authentication-method domain -role ci_readonly
그 결과로 생성되는 역할 및 사용자 로그인은 다음과 같습니다. 실제 출력은 다음과 같이 다를 수 있습니다.

....
Role Command/ Access
Vserver Name Directory Query Level
---------- ------------- --------- ------------------ --------
cluster1 ci_readonly DEFAULT read only
cluster1 ci_readonly security readonly
....
....
cluster1::security login> show
Vserver: cluster1
Authentication Acct
UserName    Application   Method      Role Name      Locked
---------   -------      ----------- -------------- --------
ci_user     ontapi      password    ci_readonly   no
....


== 문제 해결

이 데이터 수집기에서 문제가 발생할 경우 다음과 같은 방법을 시도해 보십시오.

[cols="2*"]
|===
| 문제: | 다음을 시도해 보십시오. 


| ONTAP REST 데이터 수집기를 생성하려고 하면 다음과 같은 오류가 표시됩니다.
구성: 10.193.70.14: 10.193.70.14의 ONTAP REST API를 사용할 수 없음: 10.193.70.14 /api/cluster:400 잘못된 요청을 가져오지 못했습니다 | 이는 REST API 기능이 없는 9.6)와 같은 ONTAP ONTAP 어레이가 원인일 수 있습니다. ONTAP 9.14.1은 ONTAP REST Collector에서 지원하는 최소 ONTAP 버전입니다. 사전 REST ONTAP 릴리스에서 "400 Bad Request" 응답이 예상되어야 합니다.

REST를 지원하지만 9.14.1 이상이 아닌 ONTAP 버전의 경우 다음과 같은 메시지가 표시될 수 있습니다.
구성: 10.193.98.84: 10.193.98.84의 ONTAP REST API 사용 불가: 10.193.98.84: 10.193.98.84: ONTAP REST API at 10.193.98.84 사용 가능: cheryl5-cluster-2 9.10.1 a3cb3247-3d3c-11ee-8ff3-005056b364a7 
|===
추가 정보는 에서 찾을 수 있습니다 link:concept_requesting_support.html["지원"] 페이지 또는 에 있습니다 link:reference_data_collector_support_matrix.html["Data Collector 지원 매트릭스"].
